[workspace]

resolver = "2"

members = ["amm/contracts/*", "farm/contract", "farm/trait"]

exclude = [
    "amm/e2e-tests",
    "amm/traits",
    "helpers",
    "farm/tests",
    "amm/drink-tests",
    "test-contracts/wrapped-azero",
    "test-contracts/psp22",
]
