name: E2E tests

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:

jobs:
  tests:
    runs-on: [self-hosted, Linux, X64, large]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Cache Crates
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: E2E tests
      run: make e2e-tests-with-setup-and-teardown
