name: E2E tests

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
  merge_group:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Cache Crates
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: E2E tests
      run: make e2e-tests-with-setup-and-teardown
