name: PR checks

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: [self-hosted, Linux, X64, large]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Cache Crates
      uses: actions/cache@v3
      with:
        path: ~/.cargo 
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: Check if cargo-contract exists
      id: check-cargo-contract
      continue-on-error: true
      run: cargo contract --version

    - name: Rust checks
      run: make check-all-dockerized
