name: PR checks
on:
  push:
  workflow_dispatch:
env:
  NODE_JS_VER: 18.x
  SWANKY_NODE_VER: v1.2.0
jobs:
  checks-and-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install & display rust toolchain
      run: |
        rustup show
        rustup component add rust-src

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Cache Crates
      uses: actions/cache@v3
      with:
        path: ~/.cargo 
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_JS_VER }}

    - name: Check if cargo-contract exists
      id: check-cargo-contract
      continue-on-error: true
      run: cargo contract --version

    - name: Install cargo contract
      if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
      run: |
        sudo apt-get install binaryen
        cargo install cargo-dylint dylint-link
        # Until 2.0.0 official release, we need to specify --version expressly
        cargo install --force --locked cargo-contract --version 2.0.0

    - name: Compile contracts
      run: |
        yarn
        yarn compile

    - name: integration test
      run: cargo test

    - name: e2e test
      run: |
        sudo wget https://github.com/AstarNetwork/swanky-node/releases/download/${{ env.SWANKY_NODE_VER }}/swanky-node-${{ env.SWANKY_NODE_VER }}-ubuntu-x86_64.tar.gz
        sudo tar -zxvf swanky-node-v1.2.0-ubuntu-x86_64.tar.gz
        sudo chmod +x swanky-node
        ./swanky-node -lerror,runtime::contracts=debug &
        sleep 10
        yarn test:typechain
