name: PR checks

on:
  pull_request:

env:
  NODE_JS_VER: 18.x

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install & display rust toolchain
      run: |
        rustup show
        rustup component add rust-src

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Cache Crates
      uses: actions/cache@v3
      with:
        path: ~/.cargo 
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: Check if cargo-contract exists
      id: check-cargo-contract
      continue-on-error: true
      run: cargo contract --version

    - name: Install cargo contract
      if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
      run: |
        cargo install --version 2.1.0 --force --locked cargo-contract

    - name: Rust checks
      run: make check-all-dockerized
