name: PR checks
on:
  push:
  workflow_dispatch:
env:
  NODE_JS_VER: 18.x
  SWANKY_NODE_VER: v1.2.0
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install & display rust toolchain
      run: |
        rustup show
        rustup component add rust-src

    - name: Check targets are installed correctly
      run: rustup target list --installed

    - name: Cache Crates
      uses: actions/cache@v3
      with:
        path: ~/.cargo 
        key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rust

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_JS_VER }}

    - name: Check if cargo-contract exists
      id: check-cargo-contract
      continue-on-error: true
      run: cargo contract --version

    - name: Install cargo contract
      if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
      run: |
        cargo install --version 2.1.0 --force --locked cargo-contract

    - name: Compile contracts
      run: |
        yarn
        yarn compile

    - name: integration test
      run: cargo test

    - name: e2e test
      run: |
        make up
        make test
